# Generated by Django 5.1.6 on 2026-08-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_inventoryitem_studysession_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lifetime_xp',
            field=models.IntegerField(default=0),
        ),
    ]
