# Generated by Django 5.1.6 on 2026-08-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_profile_lifetime_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='daily_focus_goal',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='studysession',
            name='reflection',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
