# Generated by Django 5.1.6 on 2026-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_distraction_profile_daily_focus_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('study_minutes', models.PositiveIntegerField(default=60)),
                ('easy_target', models.PositiveIntegerField(default=1)),
                ('legendary_target', models.PositiveIntegerField(default=0)),
                ('reward_xp', models.PositiveIntegerField(default=80)),
                ('penalty_xp', models.PositiveIntegerField(default=50)),
                ('completed', models.BooleanField(default=False)),
                ('punished', models.BooleanField(default=False)),
            ],
        ),
    ]
