# Generated by Codex on 2026-08-23
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tracker", "0005_dailymission")]

    operations = [
        migrations.AddField(model_name="inventoryitem", name="active_until", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="inventoryitem", name="duration_minutes", field=models.PositiveIntegerField(default=0)),
        migrations.AddField(model_name="inventoryitem", name="effect", field=models.CharField(blank=True, max_length=40)),
        migrations.AddField(model_name="inventoryitem", name="quantity", field=models.PositiveIntegerField(default=1)),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.IntegerField()),
                ("reason", models.CharField(max_length=220)),
                ("kind", models.CharField(default="xp", max_length=20)),
            ],
        ),
    ]
